package cli

import (
	"bytes"
	"context"
	_ "embed"
	"errors"
	"io"
	"os"
	"slices"
	"strings"
	"time"
	"unicode"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
	"github.com/swqa7697/data-mate/internal/config"
)

func addCompletion(root *cobra.Command, override *string, build Build) {
	complete := &cobra.Command{Use: "completion", Short: "Generate shell completion", Args: cobra.NoArgs}
	for _, shell := range []string{"bash", "zsh"} {
		complete.AddCommand(&cobra.Command{Use: shell, Args: cobra.NoArgs, RunE: func(cmd *cobra.Command, _ []string) error {
			err := writeCompletion(root, shell, cmd.OutOrStdout())
			if err != nil {
				return failure("cannot write completion")
			}
			return nil
		}})
	}
	root.AddCommand(complete)
	var visit func(*cobra.Command)
	visit = func(cmd *cobra.Command) {
		cmd.ValidArgsFunction = cobra.NoFileCompletions
		cmd.Flags().VisitAll(func(f *pflag.Flag) {
			callback := cobra.NoFileCompletions
			switch f.Name {
			case "driver":
				callback = cobra.FixedCompletions([]string{"postgres"}, cobra.ShellCompDirectiveNoFileComp)
			case "tls-ca":
				callback = cobra.FixedCompletions([]string{"pem", "crt", "cer"}, cobra.ShellCompDirectiveFilterFileExt)
			case "ssh-key-file":
				callback = cobra.FixedCompletions(nil, cobra.ShellCompDirectiveDefault)
			}
			_ = cmd.RegisterFlagCompletionFunc(f.Name, callback)
		})
		if cmd.Parent() != nil && cmd.Parent().Name() == "db" && slices.Contains([]string{"edit", "scope", "remove", "test"}, cmd.Name()) {
			cmd.ValidArgsFunction = func(cmd *cobra.Command, args []string, prefix string) ([]string, cobra.ShellCompDirective) {
				out := []string{}
				if len(args) != 0 {
					return out, cobra.ShellCompDirectiveNoFileComp
				}
				ctx, cancel := context.WithTimeout(cmd.Context(), 100*time.Millisecond)
				defer cancel()
				exe, err := os.Executable()
				if err != nil {
					return out, cobra.ShellCompDirectiveNoFileComp
				}
				r, err := build.resolveRoot(*override, exe)
				if err != nil {
					return out, cobra.ShellCompDirectiveNoFileComp
				}
				profiles, _, err := config.Preview(ctx, r)
				if err != nil || ctx.Err() != nil {
					return out, cobra.ShellCompDirectiveNoFileComp
				}
				bytes := 0
				for _, p := range profiles.Connections {
					if !strings.HasPrefix(p.Alias, prefix) || strings.IndexFunc(p.Alias, unicode.IsControl) >= 0 {
						continue
					}
					if len(out) == 256 || bytes+len(p.Alias)+1 > 65520 {
						break
					}
					out = append(out, p.Alias)
					bytes += len(p.Alias) + 1
				}
				slices.Sort(out)
				return out, cobra.ShellCompDirectiveNoFileComp
			}
		}
		for _, child := range cmd.Commands() {
			visit(child)
		}
	}
	visit(root)
}

//go:embed completion_bash.sh
var bashAdapter string

func writeCompletion(root *cobra.Command, shell string, out io.Writer) error {
	var generated bytes.Buffer
	if shell == "bash" {
		if err := root.GenBashCompletionV2(&generated, true); err != nil {
			return err
		}
		_, err := io.WriteString(out, generated.String()+bashAdapter)
		return err
	}
	if err := root.GenZshCompletion(&generated); err != nil {
		return err
	}
	source := generated.String()
	replacements := [][2]string{
		{`words=("${=words[1,CURRENT]}")`, `words=("${(@)words[1,CURRENT]}")`},
		{`out=$(eval ${requestComp} 2>/dev/null)`, `local -a safeWords
    safeWords=("${(@Q)words}")
    out=$("${safeWords[1]}" __complete "${safeWords[@]:1}" 2>/dev/null)`},
		{`if eval _describe $keepOrder "completions" completions $flagPrefix $noSpace; then`, `local -a describeFlags
        describeFlags=()
        if [[ -n "$flagPrefix" ]]; then describeFlags=(-P "${flagPrefix#-P }"); fi
        if _describe ${=keepOrder} "completions" completions "${describeFlags[@]}" ${=noSpace}; then`},
	}
	for _, replacement := range replacements {
		if strings.Count(source, replacement[0]) != 1 {
			return errors.New("unsupported pinned completion generator")
		}
		source = strings.Replace(source, replacement[0], replacement[1], 1)
	}
	_, err := io.WriteString(out, source)
	return err
}
